name: Build

on:
  workflow_dispatch:

env:
  BASH_ENV: ~/.profile

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
    runs-on: [ "${{ matrix.os }}" ]
    steps:
      - name: Add PATH
        if: ${{ matrix.os == 'Windows' }}
        run: echo "C:\\actions-runner\\node" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: "recursive"
          set-safe-directory: false
          repository: RedwoodMMO/Backend
          ref: ${{ github.event_name == 'workflow_call' && 'refs/heads/' || '' }}${{ github.event_name == 'push' && github.ref || inputs.branch }}
          token: ${{ secrets.PAT }}
      - name: Install dependencies
        run: yarn
      - name: Build prisma executable
        run: yarn build

