name: Build

on:
  workflow_dispatch:

env:
  BASH_ENV: ~/.profile

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
    runs-on: [ "${{ matrix.os }}" ]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Build prisma executable
        run: yarn build
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/prisma*
